### PR TITLE
Misc Fixes

### LINKED ISSUE #14: Add no works placeholder

### LINKED ISSUE #20: Placeholder for Under Construction

### PR DESCRIPTION
**Pull request by razakhawaja**
Adds placeholders for projects.
Brings back tabs.
Some content fixes in existing projects.
Responsive iframes.
Tailwind breakpoints not working in SSG markdown for some reason. Removed usage of breakpoints for now.
Jumbotron text size increased.
Team information is now optional in overview.
Fixes a bug in prev-next widget to not link to hidden projects.

Resolves #20 
Resolves #14

### CODE REVIEW

File: containers/Project/index.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ const ProjectDetails = ({
       <PrevNextProjects allProjects={allProjects} currentProject={project} />
     </div>
   ) : (
-    <div>nope</div>
+    <></>
```
Comment (hamza1220) [inline containers/Project/index.tsx:25]: Do we want to add a spinner here instead? If not can use the `&&` syntax instead of the ternary if and we wont need an else case like this

File: pages/project/[project].tsx [hunk 2]
```diff
@@ -16,10 +16,12 @@ export const getStaticProps = async (context) => {
...
-  const allProjects = Object.keys(allProjectsDict).map((url) => ({
-    ...allProjectsDict[url],
-    url,
-  }));
+  const allProjects = Object.keys(allProjectsDict)
+    .map((url) => ({
+      ...allProjectsDict[url],
+      url,
+    }))
+    .filter((project) => project.hide === false);
```
Comment (hamza1220) [inline pages/project/[project].tsx:24]:
```suggestion
    .filter((project) => !project?.hide);
```

Also hide should be an optional field in a project. If hidden, have it. Otherwise not necessary.

File: public/info/works/under-construction.md [hunk 3]
```diff
@@ -0,0 +1 @@
+# Coming Soon.
```
Comment (hamza1220) [inline public/info/works/under-construction.md:1]: Are you sure we don't want any kind of styling here?

Comment (razakhawaja) [reply public/info/works/under-construction.md:1]: yes boss

**Review by hamza1220 — APPROVED** [review]
